- name: Ensure Hortonworks repositories are present
  copy: >
    src={{ item }}
    dest=/etc/yum.repos.d/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - hdp.repo
    - ambari.repo
  tags:
    - zookeeper
    - repos

- name: Install Java and ZooKeeper
  yum: name={{ item }} state=present enablerepo=HDP-1.3.0.0
  with_items:
    - java-1.7.0-openjdk
    - zookeeper-server
  tags:
    - zookeeper
    - pkgs

#
# Hortonworks' packages are buggy in regards
# to how they create users and groups. This
# below will ensure sanity
#
- name: Ensure the zookeeper users default group is the zookeeper group
  user: >
    name=zookeeper
    createhome=no
    state=present
  tags:
    - zookeeper
    - pkgs

#
# End fix
#
