- name: "Ensure Hortonworks repositories are present"
  copy: >
    src={{ item }}
    dest=/etc/yum.repos.d/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - hdp.repo
    - ambari.repo
  tags:
    - zookeeper
    - repos
    - files

- name: "Install Java and ZooKeeper"
  yum: >
    name={{ item }}
    state=present
    enablerepo=HDP-1.3.0.0
  with_items:
    - java-1.7.0-openjdk
    - zookeeper-server
  tags:
    - zookeeper
    - pkgs

- name: "Make sure the zookeeper group exists"
  group: >
    name=zookeeper
    state=present
    system=yes
  tags:
    - zookeeper
    - users
