- name: Ensure Hortonworks repositories are present
  copy: >
    src={{ item }}
    dest=/etc/yum.repos.d/{{ item }}
  with_items:
    - hdp.repo
    - ambari.repo
  tags:
    - zookeeper
    - repos

- name: Install Java and ZooKeeper
  yum: name={{ item }} state=present enablerepo=HDP-1.3.0.0
  with_items:
    - java-1.7.0-openjdk
    - zookeeper-server
  tags:
    - zookeeper
    - pkgs

#
# Hortonworks' packages are buggy in regards
# to how they create users and groups. This
# below will ensure sanity
#
- name: Ensure the zookeeper exists
  group: >
    name=zookeeper
    gid=498
    state=present
  tags:
    - zookeeper
    - pkgs

- name: Ensure the zookeeper users default group is the zookeeper group
  user: >
    name=zookeeper
    uid=498
    createhome=no
    group=zookeeper
    state=present
  tags:
    - zookeeper
    - pkgs

#
# End fix
#
- name: Add the zookeeper firewall rules file
  template: src=iptables.j2 dest=/etc/sysconfig/iptables mode=0600 backup=no
            owner=root group=root
  tags:
    - zookeeper
    - firewall
