- name: "Install Java and ZooKeeper"
  yum: >
    name={{ item }}
    state=present
    enablerepo=HDP-1.3.0.0
  with_items:
    - java-1.8.0-openjdk
    - zookeeper-server
  when: ansible_distribution_major_version|int <= 6
  tags:
    - zookeeper
    - pkgs

- name: "Install Java and ZooKeeper"
  yum: >
    name={{ item }}
    state=present
    enablerepo=mesosphere
  with_items:
    - java-1.8.0-openjdk
    - mesosphere-zookeeper
  when: ansible_distribution_major_version|int >= 7
  tags:
    - zookeeper
    - pkgs

- name: "Set /etc/init.d script name to zookeeper-server"
  set_fact:
      zookeeper_initd_script=zookeeper-server
  when: ansible_distribution_major_version|int <= 6
  tags:
    - zookeeper
    - services

- name: "Set service name to zookeeper"
  set_fact:
    zookeeper_initd_script=zookeeper
  when: ansible_distribution_major_version|int >= 7
  tags:
    - zookeeper
    - services

- set_fact:
    zookeeper_log4j_prop: "{{ zookeeper_log4j_prop|default('INFO,ROLLINGFILE') }}"
  when: ansible_distribution_major_version|int <= 6
  tags:
    - zookeeper
    - pkgs

- set_fact:
    zookeeper_log4j_prop: "{{ zookeeper_log4j_prop|default('INFO,CONSOLE') }}"
  when: ansible_distribution_major_version|int >= 7
  tags:
    - zookeeper
    - pkgs

- name: "Set logging level (CentOS 6)"
  lineinfile: >
    dest=/usr/bin/zookeeper-server
    regexp='{{ item.regex }}'
    line='{{ item.line }}'
  with_items:
    - { regex: "^export ZOO_LOG4J_PROP=", line: "export ZOO_LOG4J_PROP={{ zookeeper_log4j_prop }}" }
  when: ansible_distribution_major_version|int <= 6
  notify: "Restart ZooKeeper"
  tags:
    - zookeeper
    - pkgs

- name: "Set logging level (CentOS 7)"
  lineinfile: >
    dest=/opt/mesosphere/zookeeper/bin/zkEnv.sh
    regexp='{{ item.regex }}'
    line='{{ item.line }}'
  with_items:
    - { regex: "^    ZOO_LOG4J_PROP=", line: "    ZOO_LOG4J_PROP={{ zookeeper_log4j_prop }}" }
  when: ansible_distribution_major_version|int >= 7
  notify: "Restart ZooKeeper"
  tags:
    - zookeeper
    - pkgs
