- name: "Install ZooKeeper"
  apt: >
    name={{ item }}
    state=present
  with_items:
    - zookeeper
    - zookeeperd
    - zookeeper-bin
    - libzookeeper2
  tags:
    - zookeeper
    - pkgs

- name: "Set /etc/init.d script name to zookeeper"
  set_fact:
    zookeeper_initd_script=zookeeper
  tags:
    - zookeeper
    - services

- name: "Make sure zookeeper-client is present"
  copy: >
    src=debian-zookeeper-client
    dest=/usr/bin/zookeeper-client
    owner=root
    group=root
    mode=0755
  tags:
    - zookeeper
    - files
