#####################
# CentOS
- include: centos.yml
  when: ansible_distribution == 'CentOS'

#####################
# Ubuntu
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

#####################
# Debian
- include: debian.yml
  when: ansible_distribution == 'Debian'

- name: Copy the configuration file for ZooKeeper
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  notify: Restart ZooKeeper
  tags:
    - zookeeper
    - files
    - configs

- name: Initialize ZooKeeper
  template: >
    src=myid.j2
    dest=/var/lib/zookeeper/myid
    owner=zookeeper
  tags:
    - zookeeper
    - configs

- name: Ensure /var/log/zookeeper is present
  file: >
    path=/var/log/zookeeper
    state=directory
  tags:
    - zookeepers
    - files

- name: Make sure ZooKeeper is running
  service: name=zookeeper-server state=running enabled=yes runlevel=5

- name: Add the zookeeper firewall rules file
  template: >
    src=iptables-zookeeper.j2
    dest=/etc/iptables.d/zookeeper
    mode=0600
    backup=no
    owner=root
    group=root
  tags:
    - firewall

- name: Install rsyslog config
  template: >
    src=rsyslog.conf.j2
    dest=/etc/rsyslog.d/zookeeper.conf
    owner=root
    group=root
    mode=0644
    backup=no
  notify:
    - Restart rsyslogd
  tags:
    - zookeeper
    - rsyslogd
